version: '3.1'

services:

  mautic:
    build:
      context: .
    image: mautic/mautic:apache
    restart: always
    ports:
      - 8001:80
    environment:
      MAUTIC_DB_HOST: mautic_mysql
      MAUTIC_DB_NAME: mautic
      MAUTIC_DB_USER: mautic
      MAUTIC_DB_PASSWORD: mautic@secret
    volumes:
      - ../plugins:/var/www/html/plugins
    depends_on:
      - mautic_mysql

  mautic_mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mautic
      MYSQL_USER: mautic
      MYSQL_PASSWORD: mautic@secret
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
